### ISSUE TITLE
Interrupting parent can result in orphaned plugins hot-looping

### ISSUE THREAD

**Issue by phinze** [hashicorp/go-plugin#10]
Filing this here so we can think about it:

https://github.com/hashicorp/terraform/issues/5043#issuecomment-190341894

Unfortunately we don't have repro, but we do have one user reporting it.

**Comment by mitchellh** [comment]
Hm, a repro would help a lot. We don't double fork the plugins so when the parent dies, the plugins should also die. I can introduce a test case for this, but thats the behavior I've seen.

**Comment by mitchellh** [comment]
Closing this until we see it again. Its been awhile :D
