### ISSUE TITLE
feature-request: do not pass the whole os.Environ to plugin

### ISSUE THREAD

**Issue by olegsu** [hashicorp/go-plugin#103]
Hey ppl :-D 
Thanks for great system!
Have a feature request, on line https://github.com/hashicorp/go-plugin/blob/master/client.go#L523, the host is passing the whole set of the environment variables to the plugins.
I'd like to have the ability to skip it (for security reasons).

**Comment by ghostsquad** [comment]
Yes please

**Comment by tomhjp** [comment]
Sorry this went unanswered for so long, but thanks for raising it. There's finally a [ClientConfig.SkipHostEnv](https://github.com/hashicorp/go-plugin/blob/303d84fc850fc2ad18981220339702809f8be06a/client.go#L242) option so you can do exactly this.
