### ISSUE TITLE
AutoMTLS does not work with brokering from plugin to host.

### ISSUE THREAD

**Issue by azdagron** [hashicorp/go-plugin#109]
With `AutoMTLS=true`, brokered connections dialed from the plugin back to the host fail with `transport: authentication handshake failed: x509: certificate is valid for localhost, not unused`.

Additionally, brokering with AutoMTLS requires the use of broker.AcceptAndServe since the autogenerated TLS configuration is not exported and therefore cannot be used to set up a gRPC server to use with the listener returned from `broker.Accept`.

**Comment by fairclothjm** [comment]
Fixed in https://github.com/hashicorp/go-plugin/pull/193
