### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by krzysztofantczak** [hashicorp/go-plugin#11]
Hi,

Would it be possible to see more implementation examples? I'm wrapping my head around on how to create dynamically loaded plugins ;/

**Comment by Smuerdt** [comment]
Hey, maybe it helps to have a look in the plugin architecture of all the terraform plugins. I also needed a long time but this helped me a lot. 

Plugin Mechanism:
https://github.com/hashicorp/terraform/tree/master/plugin

Builtin Plugins which are dynamically loaded:
https://github.com/hashicorp/terraform/tree/master/builtin

**Comment by darren-west** [comment]
I would also agree an example of invoking a separate binary would be of great use here.

**Comment by krzysztofantczak** [comment]
Darren, the easiest way for me was to take start here https://github.com/hashicorp/otto-example-app-plugin and here https://github.com/hashicorp/otto/tree/v0.2.0 (You are interested with RPC and PLUGIN directories, also app/app.go and app/factory.go and command/plugin_manager.go - You can c&p them and use right away, just to start). Also terraform as reference for other features that are not available in otto was a great help. If You do it right, You can extract basic implementation and run your plugins with few clicks (yeah, without much digging at the beginning ;)).

Keep in mind, go-plugin seems really "raw" idea. Most of real features (like plugin manager) need to be implemented on top of it.

**Comment by JalfResi** [comment]
Just started to explore this package and should add that whilst the idea is simple in principle (plugin is executable, start process and RPC command between the host and plugin process) the implementation is way more complicated than that!

Maybe including a simple plugin manager as part of the project that covers most use cases for new users? Something that loads all the executable plugins from a specified directory, that adhere to a specific single interface? People could get up and running pretty quickly with something like that.

In fact, that is exactly what I need so once I've got something written I may be able to put together a pull request with that.

**Comment by krzysztofantczak** [comment]
@JalfResi https://github.com/hashicorp/otto/blob/v0.2.0/command/plugin_manager.go - does the trick as plugin manager. Atm. i'm using this code with watcher on plugins directory - works pretty well. Also, good idea to create some real world examples.

**Comment by rvanantwerp** [comment]
Any updates on this? I'm trying (and failing) to produce even the most basic example of two binaries communicating using this library. Even splitting the example into two source files would help immensely, but I can't seem to get it to compile without including the implementation of Greeter(), which defeats the purpose of abstracting that implementation out into a plugin. Reading through terraform's code is tedious, at best, and in my opinion should never be a requirement to understanding a library. 

I'd be happy to submit a PR for documentation/examples when I understand this better, but I need some direction to move forward.

**Comment by JalfResi** [comment]
Have to agree with the above poster; had exactly the same problem with the example being in one file and other hashicorp projects focusing on internal plugins. The dependence on "Greeter" is messy to work around.

In the meantime I've had to conclude this package is just not ready for public use

**Comment by skx** [comment]
I've just worked on splitting up the single example into two binaries, which reflects how it will actually be used.  While it doesn't close this issue _entirely_ it does provide a simpler example & introduction.

**Comment by hleong25** [comment]
Here is my example of separating the simple single example into multiple binaries.

https://github.com/hleong25/hashicorp-goplugin-separate-binary-example

The main thing to get from this is that there is a library that is shared between the mainapp and plugins. The information needed is the interfaces and the plugin handshake configuration.

**Comment by mitchellh** [comment]
The PR #20 was just merged which helps this, too :)

**Comment by spiderpoison** [comment]
I want a example for Reattach

**Comment by klayyu** [comment]
thanks for the greate work, any one has the java plugin impl?
