### ISSUE TITLE
net/rpc only plugin without grpc bloat

### ISSUE THREAD

**Issue by nom3ad** [hashicorp/go-plugin#120]
Is it possible to create a net/rpc only implementation (both host and plugin) without bloated by gRPC dependencies? 
WIll the binaries always have all modules listed _go.sum_ file?

**Comment by mitchellh** [comment]
It will always be in `go.sum`. I'm unsure if it will always actually link it into the binary if there are no code paths calling the gRPC code. This isn't something we're interested in optimizing for.
