### ISSUE TITLE
Please create a release so changes from pull request 111 can be included into vault sdk

### ISSUE THREAD

**Issue by arykalin** [hashicorp/go-plugin#121]
Hi.
Please create a release so changes from pull request  https://github.com/hashicorp/go-plugin/pull/111 can be included into vault sdk

**Comment by jefferai** [comment]
Duplicate of https://github.com/hashicorp/vault/pull/6904.

In the future, please only open one issue, and since Vault is where you need the dep updated, that's the appropriate place.
