### ISSUE TITLE
Close plugin

### ISSUE THREAD

**Issue by pjebs** [hashicorp/go-plugin#131]
The builtin `plugin` package doesn't support closing a plugin to release its resources and make the application behave as if the plugin was never loaded in the first place: https://github.com/golang/go/issues/20461

Does the approach used in this package allow a "Close()" that releases all resources etc.

**Comment by ncabatoff** [comment]
Since the plugins are implemented as subprocesses, yes, it's easy to release all resources when you're done with a plugin.  See for example [Client.Kill](https://godoc.org/github.com/hashicorp/go-plugin#Client.Kill).
