### ISSUE TITLE
Understand how stderr/stdout is consumed

### ISSUE THREAD

**Issue by pepov** [hashicorp/go-plugin#147]
While we are getting stuck with https://github.com/terraform-providers/terraform-provider-helm/issues/498 I tried to understand how the stdout and stderr of the provider process ought to be consumed from the client side. I also tried looking at the terraform code, but had no luck to understand where and how stderr/stdout is configured to be consumed.

The helm provider uses the plugin sdk v1.9.1 which uses go-plugin v1.0.1

Any pointers would be much appreciated to help us in either understanding what should be happening with the pipe created for stderr or show us how to debug this issue further.

As I'm writing this I came across this in the latest codebase, which wasn't available in v1.0.1:
https://github.com/hashicorp/go-plugin/blob/master/grpc_server.go#L92

Is that possible, that stdout/stderr is completely omitted in go-plugin v1.0.1 and the first write to stderr causes the server process to block?

**Comment by mitchellh** [comment]
Hey pepov! Yes, it is entirely possible that stdout/stderr writes are blocked completely prior to that commit, although I feel like we would've heard from more projects if that was the case. After that commit, stdout/stderr will default to `ioutil.Discard` (effectively `/dev/null`) if stdio syncing is not enabled.

The basic background is covered in this comment here: https://github.com/hashicorp/go-plugin/pull/135#issuecomment-590518189

I'll also cc @paddycarver in here who works on Terraform SDK stuff to see if he has any feedback. I'm going to close this unless there is some action you wanted beyond this. Please let me know.

**Comment by paddycarver** [comment]
Hey @pepov, I'm interested in hearing more about why you're looking to consume stdout/stderr, and from which process. I'd love to chat a bit more about this in the hashicorp/terraform-plugin-sdk repo, if you want to start an issue over there.

**Comment by pepov** [comment]
@paddycarver thanks! Before we discuss what should/could be done over the sdk side, could we go back to the original issue to understand the context? I'm asking this because I'm not looking to consume stdout/stderr myself, I just wanted to understand how we can mitigate the blocking write issue on stderr from the plugin's point of view. Could you please look at this 
https://github.com/terraform-providers/terraform-provider-helm/issues/498 and help us figure out the way forward?

**Comment by paddycarver** [comment]
Hey @pepov, sorry for the delayed response, got a few plates spinning and this issue fell off my radar. I'll touch base with our Kubernetes provider team and see if we can't get some more information on what's going on. We can probably track that in the Helm issue you linked.
