### ISSUE TITLE
[Question] how does this framework work in Docker/k8s environment

### ISSUE THREAD

**Issue by imaffe** [hashicorp/go-plugin#159]
Just wondering if HashCorp has already applied this plugin framework in Docker/k8s environments. (I think it should be OK since HashCorp has been working closely with cloud-native applications)

Thanks so much if anyone could give some information on this :)

**Comment by lsnow99** [comment]
I run it in k8s - my experience has been just to create a custom docker base image with all the requirements for both the plugin and the go program, and otherwise it runs normal, nothing special about it being in Docker/k8s.
