### ISSUE TITLE
Allow to config grpc.DialOption in the config

### ISSUE THREAD

**Issue by lujiajing1126** [hashicorp/go-plugin#166]
To enable tracing in the client side, we need to allow users pass custom `grpc.DialOption` in the config while initializing.

Some documents here,

https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc

As users can already pass `grpc.ServerOption`, we don't need to do anything for the server-side.

**Comment by azdagron** [comment]
This would also be incredibly useful for us on the [SPIRE](https://github.com/spiffe/spire) project for similar reasons. We want to log and provide metrics around each RPC call. Currently we wrap the interfaces to provide this functionality, but that is a LOT of boilerplate and is error prone. The ability to set the client side interceptor dial options (either directly or indirectly) would allow us to implement this generically.

**Comment by mitchellh** [comment]
I'm totally supportive of this. I haven't looked at the best way to do it and this isn't really a priority for us as maintainers. I think if someone made a rough proposal and opened a PR though we'd be happy to merge. We do ask folks share their thoughts on UX/API before the PR just so we can agree on that first. Thanks!

**Comment by lujiajing1126** [comment]
> I'm totally supportive of this. I haven't looked at the best way to do it and this isn't really a priority for us as maintainers. I think if someone made a rough proposal and opened a PR though we'd be happy to merge. We do ask folks share their thoughts on UX/API before the PR just so we can agree on that first. Thanks!

Thanks for the reply. Please check the modified PR #168 for the draft of the design.

**Comment by mitchellh** [comment]
Thanks, done #168
