### ISSUE TITLE
Function within plugin uses it's own client on a different IP address

### ISSUE THREAD

**Issue by kkol26** [hashicorp/go-plugin#175]
Beginner here not sure if using this package is most suitable for this use case but,

Trying to design a plugin which works by sending commands to a PLC connected by ethernet. Resorting to this method because go-plugins have no windows support. 

(If there's another alternative to go-plugins on windows I would be glad to know about them)

The error below appears when the commands are sent to the PLC.
Error: rpc error: code = Unknown desc = write udp 192.168.x.x:9600->192.168.x.x:9600: use of closed network connection

Is it impossible to use the go-plugin package to send commands over another connection?

**Comment by tomhjp** [comment]
Sorry for the long delay replying, but this doesn't sound like a use-case that go-plugin can service. It expects both processes to be on the same machine as the client actually spawns the plugin sub-process itself, and then manages connecting to it and its lifecycle.
