### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by ghost** [hashicorp/go-plugin#180]
I tried the examples but i keep getting:
```
$ KV_PROTO=grpc ./kv Put hello world
2021-10-04T02:32:38.694+0200 [DEBUG] plugin: starting plugin: path=./kv-plugin args=["./kv-plugin"]
Error: exec: "./kv-plugin": file does not exist
```
I keep getting the error Error: exec: "./plugin-here": file does not exist
I tried kv and the basic example but i keep getting this error

and the file does indeed exist:
```
plugin-go
  |___ main.go
go.mod
go.sum
kv
kv-plugin
main.go
```

**Comment by Vanclief** [comment]
Check example folder or this guide: https://eli.thegreenplace.net/2021/plugins-in-go/

Thats how I got started, but I can assure you that the module works.
