### ISSUE TITLE
Inversion of Control - possible?

### ISSUE THREAD

**Issue by tigerinus** [hashicorp/go-plugin#211]
First of all, this is a great project.

As I read, the host loads the plugins typically.

It is possible to do it the other way, e.g. each plugin registers itself with the host when the process containing that plugin runs?

Thanks.

**Comment by fairclothjm** [comment]
@tigerinus Hi, this is not currently supported by go-plugin. The host process is responsible for launching the plugin binaries. Please see https://github.com/hashicorp/go-plugin/blob/master/docs/internals.md#go-plugin-internals

**Comment by tigerinus** [comment]
I think what I can do is provide a list of plugins as a configuration file or something like that. When host runs, it loads the plugins based on the configuration file, much like the original Spring Boot XML for the same purpose in the good old time.
