### ISSUE TITLE
Files are not closed on windows

### ISSUE THREAD

**Issue by MarcosDY** [hashicorp/go-plugin#232]
[additionalNotesAboutCommand](https://github.com/hashicorp/go-plugin/blob/main/notes_windows.go#L17-L39) is opening a file using `elf`, `macho` and `pe`  to extract information,
but those files are never closed. 
This can cause issues when another process is trying to open them again or try to remove.

**Comment by rturner3** [comment]
Is there any upcoming planned release with the fix for this issue? This is preventing github.com/spiffe/spire from being able to update to the latest version of github.com/hashicorp/vault/sdk.

**Comment by evan2645** [comment]
@rturner3 [v1.4.10](https://github.com/hashicorp/go-plugin/releases/tag/v1.4.10) has been released which includes this fix, thank you @fairclothjm for your help!
