### ISSUE TITLE
Be able to just implement a gRPC only pluginmap 

### ISSUE THREAD

**Issue by manther** [hashicorp/go-plugin#34]
Can't implement pluginmap as a map of grpcplugins

var PluginMap = map[string]plugin.GRPCPlugin

Have to use map[string]plugin.Plugin

and implement client and server funcs for both grpc flavor and rpc flavor.

**Comment by mitchellh** [comment]
We didn't want to break backwards compatibility so we instead recommend just embedding this into your GRPCPlugin: https://github.com/hashicorp/go-plugin/blob/03136dc196bf3ce9ac05bb584e56d61ffeb2f1a7/plugin.go#L48

That's why that exists. A bit clunky but lets you do pure gRPC.

**Comment by manther** [comment]
Sweet thanks!
