### ISSUE TITLE
defer client.Kill() - terraform provider clean up

### ISSUE THREAD

**Issue by srinarayanant** [hashicorp/go-plugin#46]
Hi Team ,
is there a recommended way to hook the defer client.Kill() to a terraform providers clean up method .

I could use the [func providerConfigure(d *schema.ResourceData) (interface{}, error) ] to initialize the plugin , but will need to kill the client plugin after all the terraform operations are done

Thanks & Regards,
Sri

**Comment by srinarayanant** [comment]
We have sidestepped the problem for  now making the python plugin a singular instance by checking the listening port

**Comment by mitchellh** [comment]
There isn't a good way to hook into this right now and its up to the parent application to provide this (if they want). "At shutdown" hooks in general in processes are really unsafe (see various Go topics about it) so they aren't recommended. If you want, you can ask Terraform about this functionality.
