### ISSUE TITLE
panic: runtime error: integer divide by zero while initing the client 

### ISSUE THREAD

**Issue by srinarayanant** [hashicorp/go-plugin#48]
```
2017/10/20 09:54:02  ok starting to client 
2017-10-20T09:54:02.204-0400 [DEBUG] plugin: starting plugin: path=/usr/bin/sh args="[sh -c python3 /home/terraform-provider-vcloud-director/plugin-python/plugin.py]"
2017-10-20T09:54:02.204-0400 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/sh
panic: runtime error: integer divide by zero

goroutine 14 [running]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc4200c4200, 0x0, 0xc42001e780)
	/home/terraform-provider-vcloud-director/go/src/google.golang.org/grpc/clientconn.go:930 +0xf50
google.golang.org/grpc.(*addrConn).connect.func1(0xc4200c4200)
	/home/terraform-provider-vcloud-director/go/src/google.golang.org/grpc/clientconn.go:736 +0x2f
created by google.golang.org/grpc.(*addrConn).connect
	/home/terraform-provider-vcloud-director/go/src/google.golang.org/grpc/clientconn.go:735 +0x400
[root@worker3 test]# 
```

I see the above error but no specific message why its happening 

https://github.com/srinarayanant/terraform-provider-vcloud-director/blob/master/go/src/test/test.go

Above is the link to the source file , used as a test which throws this error.

This was working fine for a while till I had updated rpc interface , but now reverting the changes still the problem persists.

**Comment by mitchellh** [comment]
Hey there. Thanks for this. I've been trying to reproduce this with gRPC and haven't been able to. IF you have a reliable repro, can you try to post steps so that I can try it? Also, can you please set the Go environment variable that dumps all stack frames? I believe that is `GOTRACEBACK=2`

**Comment by srinarayanant** [comment]
Hi @mitchellh  , 
I was able to get it work but moving a older version of the grpc library google.golang.org/grpc.
I was switching environment machines , moving from one centos to another and since I did a new go get the issue started to appear. 

I then moved folders of the external library one by one from a working older copy which had not be git updated and things started to work once I moved the google.golang.org repo.
As of now I have vendored the working copy , so I presume the latest of google.golang.org. should have the issue. Else I will commit a copy of the failing code into a vendor_fail folder


https://github.com/grpc/grpc-go/issues/1602

I have posted an issue to the grpc site .Link above / Not sure if this is the right repo  for google.golang.org


Working copy of google.golang.org  - vendored repo

https://github.com/srinarayanant/terraform-provider-vcloud-director/tree/master/go/src/vendor/google.golang.org

**Comment by srinarayanant** [comment]
result with GOTRACEBACK=2
https://gist.github.com/srinarayanant/168e400af5b617aa6173597fcfe6a262

Also , looks like the issue is gone with latest git update of google.golang.org.


Please let me know if you need any more info , glad to help

**Comment by srinarayanant** [comment]
I have commited a copy of the erring package here

https://github.com/srinarayanant/terraform-provider-vcloud-director/blob/master/go/src/google.golang.org_panic.tar


To reproduce the error below steps would help

1 git clone  project https://github.com/srinarayanant/terraform-provider-vcloud-director/tree/master/go/src
2 remove the google.golang.org folder from the venodor folder.
3 tar -xvf go/src//google.golang.org_panic.tar
4 cd go/src/test -  go build and execute ./test

**Comment by mitchellh** [comment]
This does indeed look like an upstream gRPC issue. It looks like they've resolved it but I can't find a unit test around it so not sure how easy it would be to regress. Glad you figured this out though!
