### ISSUE TITLE
Bidirectional communication

### ISSUE THREAD

**Issue by krzysztofantczak** [hashicorp/go-plugin#50]
Quote:
```
Bidirectional communication. Because the plugin system supports complex arguments, 
the host process can send it interface implementations and the plugin can call back
into the host process.
```

Any example of how can we approach this? Do we need separate (g)rpc connection for that? Is there any project on github that uses this kind of functionality? Also, is it somehow possible to use one plugin from another?

**Comment by mitchellh** [comment]
Support for bidirectional communication has always existed for netrpc but was just added to gRPC recently. The example now contains bidirectional communication!
