### ISSUE TITLE
Are channels supported in a plugin interface?

### ISSUE THREAD

**Issue by mjstich** [hashicorp/go-plugin#54]
I want a plugin interface to return a channel the host can listen on for asynchronous notifications (and vice versa).  Is this supported?

**Comment by mitchellh** [comment]
Yes, but you'll have to deal with sending the data over the RPC connection. We have a bi-directional sample coming in in #50 you can look at it. It won't magically "just work" due to channels not being able to properly encapsulate errors and some other complications.
