### ISSUE TITLE
python grpc connection fails with commit #52 and beyond 

### ISSUE THREAD

**Issue by srinarayanant** [hashicorp/go-plugin#57]
The go to python grpc connection fails with commit #52 and till #51 it is working fine.
This is in relation to project http://github.com/vmware/terraform-provider-vcloud-director
===============================================================
WORKING #51

[root@centos7 go-plugin]# git show --oneline -s
e37881a Allow the server's logger to be passed in via the ServeConfig (#51)
[root@centos7 go-plugin]# 
===============================================================
FAILED #52

[root@centos7 go-plugin]#  git show --oneline -s
4b3b291 Add a Connection Broker for GRPC plugins (#52)
[root@centos7 go-plugin]# /home/terraform-provider-vcloud-director/go/src/test/test_catalog.sh
2018/01/21 04:50:30 [INFO][PLUGINLOG] __INIT__init
2018/01/21 04:50:30 [INFO][PLUGINLOG] __INIT_TestAccResourceCatalog_
=== RUN   TestAccResourceCatalogBasic
2018/01/21 04:50:30 [INFO][PLUGINLOG] __INIT__LOGGING__
2018/01/21 04:50:30 [INFO][PLUGINLOG] __INIT__testAccPreCheck_
2018/01/21 04:50:30 [INFO][PLUGINLOG] __DONE__testAccPreCheck_
2018-01-21T04:50:30.619-0500 [DEBUG] plugin: starting plugin: path=/usr/bin/sh args="[sh -c python3 /home/terraform-provider-vcloud-director/plugin-python/plugin.py]"
2018/01/21 04:50:30 [INFO][PLUGINLOG] __INIT__func providerConfigure
2018-01-21T04:50:30.620-0500 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/sh
2018-01-21T04:50:31.013-0500 [DEBUG] plugin.sh: INFO:root:Already running / Not starting new server
Error: plugin "PY_PLUGIN" doesn't support gRPC
exit status 1
[root@centos7 go-plugin]# 

===============================================================
FAILED #55

[root@centos7 go-plugin]#  git show --oneline -s
485ef45 Provide a context for managing the lifecycle of gRPC plugins (#55)
[root@centos7 go-plugin]# /home/terraform-provider-vcloud-director/go/src/test/test_catalog.sh 
2018/01/21 04:47:46 [INFO][PLUGINLOG] __INIT__init
2018/01/21 04:47:46 [INFO][PLUGINLOG] __INIT_TestAccResourceCatalog_
=== RUN   TestAccResourceCatalogBasic
2018/01/21 04:47:46 [INFO][PLUGINLOG] __INIT__LOGGING__
2018/01/21 04:47:46 [INFO][PLUGINLOG] __INIT__testAccPreCheck_
2018/01/21 04:47:46 [INFO][PLUGINLOG] __DONE__testAccPreCheck_
2018-01-21T04:47:46.084-0500 [DEBUG] plugin: starting plugin: path=/usr/bin/sh args="[sh -c python3 /home/terraform-provider-vcloud-director/plugin-python/plugin.py]"
2018/01/21 04:47:46 [INFO][PLUGINLOG] __INIT__func providerConfigure
2018-01-21T04:47:46.084-0500 [DEBUG] plugin: waiting for RPC address: path=/usr/bin/sh
2018-01-21T04:47:46.475-0500 [DEBUG] plugin.sh: INFO:root:Already running / Not starting new server
Error: plugin "PY_PLUGIN" doesn't support gRPC
exit status 1
[root@centos7 go-plugin]#

**Comment by mitchellh** [comment]
@briankassouf can you take a look at this

**Comment by briankassouf** [comment]
Thanks for the report, and sorry you ran into this!

The `GRPCPlugin` interface recently changed from:

```
type GRPCPlugin interface {
	GRPCServer(*grpc.Server) error
	GRPCClient(*grpc.ClientConn) (interface{}, error)
}
```
To:

```
type GRPCPlugin interface {
	GRPCServer(*GRPCBroker, *grpc.Server) error
	GRPCClient(context.Context, *GRPCBroker, *grpc.ClientConn) (interface{}, error)
}
```
Applications that use the latest code will need to update the plugin clients to use these new interfaces. The changes happened in #52 and #55 and there is some context availible in those PRs, but I'll also outline the changes here: 

#52 added a gRPC connection broker that can broker additional connections between the plugin and client. It's useful for plugins that need bi-directional communication. The implementation took a lot of inspiration from the existing broker for netRPC plugins, and therefore was added to the interface's function signatures. 

#55 now provides a context to the client process by passing it through the interface. This context helps to manage the lifecycle of the gRPC connection. When go-plugin detects the plugin process has died it also cancels the context.

**Comment by srinarayanant** [comment]
@briankassouf 
Thank You , Thant fixed the issue .

https://github.com/vmware/terraform-provider-vcloud-director/pull/13
