### ISSUE TITLE
Is it possible to extend the life of a plugin function's interface parameter?

### ISSUE THREAD

**Issue by e-nikolov** [hashicorp/go-plugin#71]
When a plugin function accepts an interface argument, supplied by the base process (as in the bidirectional example), it seems that the parameter is only usable until the plugin function returns and after that the grpc connection for that interface closes. 

Is there a recommended way to allow that parameter be usable for as long as the plugin is running? So that I can for instance have an `Init(service Service)` method of the plugin which can be used by the base application to supply an instance of the `service` interface to the plugin, which can then be called from various go routines after the Init function has returned?

**Comment by briankassouf** [comment]
This should already be possible with both netRPC and gRPC plugins. The Client will just need to manage the lifecycle of the argument. The argument's server would be created on `Init()` and then stopped at a later time like a `Cleanup()` method

**Comment by heaxo** [comment]
@briankassouf Hello, do you have any examples

**Comment by heaxo** [comment]
@briankassouf I have removed the close and stop codes for parameter services in the Server and Client interface methods, which allows for long-term invocation. Is this appropriate? Is there any other better way
