### ISSUE TITLE
GRPCBroker's Dial timeout

### ISSUE THREAD

**Issue by j0hnwhyte** [hashicorp/go-plugin#89]
Hey
I'm posting after trying for hours, the plugin structure is working fine, but setting up the bidirectional communication for my program is proving to be a real challenge.

I think I understand how this works, but probably I'm missing something important. Basically I've started the plugin, and extracted the broker to use it in the main code (host), it looks like this:
```go
	// Assign the implementation, calls to this are RPC now
	test := raw.(sdk.Test_rpc_container)

	// Bootstrap the connections to the module?
	h := HeartbeatService{}
	hbServiceServer := &sdk.GRPCHBServiceServer{Impl: &h}

	var svr *grpc.Server
	serverFunc := func(opts []grpc.ServerOption) *grpc.Server {
		svr = grpc.NewServer(opts...)
		proto.RegisterHeartbeatServer(svr, hbServiceServer)

		return svr
	}

	go test.Broker.AcceptAndServe(1, serverFunc)
```

so the Broker should be listening to connections on channel 1. It's hardcoded, yes.

And in the plugin I have this:
```go
func (s *FuncRPCServer) Call(ctx context.Context, req *proto.CallRequest) (*proto.CallResponse, error) {

	conn, err := s.broker.Dial(1)
	if err != nil {
		return nil, errors.New("I HAZ FAIL")
	}
```

This setup is very close to the bidirectional example, the RPC server creates the channel once the function Call gets called, yet it goes into timeout after 5 secs failing here.

So... this is the point where I ask for help, as the documentation doesn't seem to describe anything particular about this.

Please tell me if you need more details. Thanks for the useful library.

Thanks

**Comment by j0hnwhyte** [comment]
...by the way, now that I think about it.. is the broker object specific to the plugin instance (so it's the same for all the lifetime of the plugin) or is it generated at every request? In the second case it would make sense that I kept an old broker and a new one just got generated in the following request. Which case is true?

**Comment by mitchellh** [comment]
cc @briankassouf if you have a sec here

**Comment by j0hnwhyte** [comment]
Just for adding context, I'm trying to build a system for the plugin to call services on the server via different streams of the same socket (if I get the names right). Each plugin has n streams that in the server point all to the same services.

As an experiment, I'm trying to get the plugin to talk to a service called Heartbeat that checks if the server is still alive (otherwise the plugin kills itself in order to avoid being orphan), this should communicate with its .proto definition, through a specific stream, to the instance of the `HeartbeatService`. This should apply to all the loaded plugins.

I hope that's clear enough for the use case.

**Comment by briankassouf** [comment]
@j0hnwhyte What error is coming back from the `s.broker.Dial(1)` call?

**Comment by briankassouf** [comment]
Sorry- didn't mean to close

**Comment by j0hnwhyte** [comment]
Connection timeout, the one after 5 seconds

**Comment by briankassouf** [comment]
How much time is going by between calling `AcceptAndServe` in your application and the plugin calling `Dial`? Currently go-plugin will timeout and close a stream if it doesn't see a client connection in 5 seconds. 

Also just to clarify, the grpcBroker doesn't reuse the same socket, each accept call opens a new socket for that particular server type, so it's best to open one per plugin instead of one per request.

**Comment by briankassouf** [comment]
So the broker also expects a 1:1 mapping of Accept calls to Dial calls for any given broker ID. My recommendation would to create a single connection by calling `Dial` upon plugin creation/initialization, store that and reuse it later. 

We use a similar strategy in Vault when creating a plugin. The setup gRPC call setups a connection on either end: https://github.com/hashicorp/vault/blob/fb3511922ac864f1d3f6921ee2da0e112d94a818/logical/plugin/grpc_backend_client.go#L197-L213

https://github.com/hashicorp/vault/blob/fb3511922ac864f1d3f6921ee2da0e112d94a818/logical/plugin/grpc_backend_server.go#L30-L34

It does use UNIX sockets under the hood, or if those are not available it will fall back to TCP 

Hope this helps!
Going to close the issue for now, but let me know if that doesn't work for you.

**Comment by j0hnwhyte** [comment]
I can confirm that following this code made it work properly (not a piece of cake, thanks for the comments : )

Now it's perfect, thanks for the help and the library.
