### ISSUE TITLE
stdout/stderr sync not implemented for gRPC plugins 

### ISSUE THREAD

**Issue by balopat** [hashicorp/go-plugin#93]
I might be missing something completely, but it seems that the stdout/stderr sync feature is not implemented for the GRPC server path. 

The [`GRPCServer.Stdout` and `GRPCServer.Stderr` fields](https://github.com/hashicorp/go-plugin/blob/master/grpc_server.go#L51-L52) are not used anywhere. They are set up however in the same way as in `RPCServer` in the common codepath in [`Serve()`](https://github.com/hashicorp/go-plugin/blob/master/server.go#L308-L309) it's just RPCServer has control over the channel, while in GRPC I guess it is not that obvious how the sync can be implemented. Is my understanding correct? 

I think this asymmetry should be documented between netRPC and gRPC! Are there any more differences? 

Logs in gRPC plugins can work using the `log`, `hclog` packages, they _are_ pointing to the old stderr.   

Workaround for getting the output of `fmt.Println()` for example to `stdErr` involves saving the old `stdErr` in a var and using that (for some reason the same trick does not work with `stdOut`):

````
var oldOut *os.File
var oldErr *os.File
// Here is a real implementation of KV that writes to a local file with
// the key name and the contents are the value of the key.
type KV struct{}

func (KV) Put(key string, value []byte) error {
	fmt.Fprintf(oldOut,"Hello, I'm the plugin putter.1\n") # this does not work
	fmt.Fprintf(oldErr,"Hello, I'm the plugin putter.2\n") # this works
	fmt.Fprintf(os.Stderr,"Hello, I'm the plugin putter.3\n") # this does not work
	fmt.Fprintf(os.Stdout,"Hello, I'm the plugin putter.4\n") # this does not work
	log.New(os.Stderr, "hihii", 0).Printf("test") # this does not work
	log.Printf("log hello:) - %v %v vs %v %v\n", os.Stdout, os.Stderr, oldOut, oldErr) # this works
	value = []byte(fmt.Sprintf("%s\n\nWritten from plugin-go-grpc", string(value)))
	return ioutil.WriteFile("kv_"+key, value, 0644)
}

func (KV) Get(key string) ([]byte, error) {
	return ioutil.ReadFile("kv_" + key)
}

func main() {
	oldOut = os.Stdout
	oldErr = os.Stderr
	plugin.Serve(&plugin.ServeConfig{
		HandshakeConfig: shared.Handshake,
		Plugins: map[string]plugin.Plugin{
			"kv_grpc": &shared.KVGRPCPlugin{Impl: &KV{}},
		},
		// A non-nil value here enables gRPC serving for this plugin...
		GRPCServer: plugin.DefaultGRPCServer,
	})
}
```` 

In comparison the Sync feature does work well in the netRPC plugin when `SyncStdout` and `SyncStderr` are set on the `plugin.ClientConfig`.

**Comment by sargun** [comment]
This kind of implements it: https://github.com/hashicorp/go-plugin/pull/113

**Comment by yurishkuro** [comment]
Why do logs need to be sent over gRPC at all? The parent process already has access to the child process's stdout/err, it could read them and forward to its own stdout/err (after splitting on `'n`). This would make implementing plugins in other languages much easier, no additional gRPC streams to support.
