### ISSUE TITLE
Revision 1b0 onward fails to work with vault plugin system

### ISSUE THREAD

**Issue by broamski** [hashicorp/go-plugin#94]
Hey there! When authoring a Vault plugin, if I vendor with any recent version of vault and with revision 1b0f5429182b3157c6f22301a77fde89bab6dbd7 or onward of this plugin, the plugin fails to properly communicate with vault.

You can test this by cloning https://github.com/hashicorp/vault-auth-plugin-example, removing the existing vendoring (vendor and Gopkg*) and starting from scratch with this `Gopkg.toml`:

```
[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "=1.0.1"

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "1b0f5429182b3157c6f22301a77fde89bab6dbd7"

```

Failing back to any previous revision and the plugin works as expected. It would appear that the `Dial` function is failing in: https://github.com/hashicorp/go-plugin/blob/f444068e8f5a19853177f7aa0aea7e7d95b5b528/grpc_broker.go#L376

I'm starting here in the event it's not strictly related to vault. Thanks!

**Comment by jefferai** [comment]
@jbardin is it expected after your recent refactoring that current go-plugin would be incompatible with prior versions?

**Comment by jbardin** [comment]
Nope, it wasn't expected, as we did the same in terraform.

There however was some unexpected issues with the proto namespacing which was being discussed, though nothing has landed from that in the plugin package. I'll take a look into it.

**Comment by jefferai** [comment]
@broamski @Albibek can you test with https://github.com/hashicorp/go-plugin/pull/97 ?

**Comment by Albibek** [comment]
It works on my side now.

**Comment by marco-m** [comment]
@jefferai @Albibek do I understand correctly that #97 fixed this bug and this ticket can be closed?

**Comment by Albibek** [comment]
Not sure, what solved it, but it did.

**Comment by jefferai** [comment]
Great, thanks!
